<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Template Page</title>
</head>

<body>
    <div class="main">
        <?php
         $row = $this->template[0];
         ?>
        <form action="/index/edit?id=<?php $row['id']?>" method="POST" enctype="multipart/form-data" target="my_iframe">
            <div class="table_template">
                <input type="hidden" name="id" value="<?=  $row['id']?>">
                <table class="form_add_template">
                    <tr>
                        <th class="header">Edit Template</th>
                    </tr>
                    <tr class="tr__control">
                        <td>
                            <p class="form_text">Name</p>
                            <input type="text" name="name" id="name" value="<?php echo $row['name']?>" autocomplete="off" />
                        </td>
                    </tr>
                    <tr class="tr__control">
                        <td>
                            <p class="form_text">Controller</p>
                            <input type="text" name="controller" value="<?php echo $row['controller'] ?>" id="controller" autocomplete="off" />
                        </td>
                    </tr>
                    <tr class="tr__control">
                        <td>
                            <p class="form_text">Action</p>
                            <input type="text" name="action" value="<?php echo $row['action'] ?>" id="action" autocomplete="off" />
                        </td>
                    </tr>
                    <tr class="tr__control">
                        <td>
                            <p class="note_text form_text">Note</p>
                            <textarea name="note" id="note" cols="25" rows="3" autocomplete="off"><?php echo $row['note'] ?></textarea>
                        </td>
                    </tr>
                    <tr class="tr__control">
                        <td>
                            <p class="form_text">file</p>
                            <input type="file" name="file" id="file" />
                        </td>
                    </tr>
                            <?php if (isset($row['file'])) {?>
                    <tr>
                        <td  style="text-align: center;font: weight 12px; ">
                        <a href='/files/<?php echo $row['file']?>' target='_blank' style="color: blue; "><?php echo $row['file']?></a>
                        </td>
                        </tr>
                            <?php }?>
                    <tr>
                        <th style="text-align: center;">
                            <a href="/index/view">View Data</a>
                        </th>
                    </tr>
                    <tr>
                        <td>
                            <iframe name="my_iframe" src=""></iframe>
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align: center">
                            <input type="submit" value="Submit" id="submit" />
                        </td>
                    </tr>
                </table>
            </div>
        </form>
    </div>
</body>

</html>