
<head>
    <style>
        th{
            font-size: 15px;
        }
        tr{
            font-size:  12px;
        }
    </style>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" />
</head><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

<body>
<table class='table table-striped table-hover'>
<tr>
    <th style="background: #fff; white-space: nowrap;" colspan="2">
    <form action="/index/search" method="post">

        <input type="text" style="width: 70%;" name="search">
        <button type="submit" style="color:#fff" class="btn btn-primary btn-lg">search</button>
    </form>
    </th>
</tr>    
    <?php if (isset($this->template)) {
        $count = 0 ?>
        <tr>
         <th>STT</th>
         <th>Name</th>
         <th>Controller</th>
         <th>Action</th>
         <th>Note</th>
         <th style="text-align: right">File</th>
     </tr>
        <?php foreach ($this->template as $row) {?>
            <?php $file  = '../files/'.$row["file"]; 
            $count=$count+1;?>
            <tr>
            <td><?php echo $count?></td>
            <td><?php echo $row['name']?></td>
            <td><?php echo $row['controller']?></td>
            <td><?php echo $row['action']?></td>
            <td><?php echo $row['note']?></td>
            <td style="text-align: right"><a target="_bland" href="<?php echo $file?>"><?php echo $row['file'] ?> 
  <i class="fas fa-file"></i></a>
                </td></td>
            </tr>
    <?php }}else{ ?> 
        <tr><th>Hiện chưa có dữ liệu</th></tr>
        <?php }?>

    <tr>
        
        <th style="text-align: center, cursor: poiner"><a href="../" >back</a></th>
    </tr>
    </table>
</body>

</html>