
<head>
    <style>
        th{
            font-size: 15px;
        }
        tr{
            font-size:  12px;
        }
        #live_search{
            position: absolute;
        }
    </style>
</head>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<body>
<table class='table table-striped table-hover'>
<tr>
    <th style="background: #fff; white-space: nowrap;" colspan="2">
    <form action="/index/search" method="post">

        <input type="text" style="width: 70%;" name="search" onkeyup="showHint(this.value)">
        <button type="submit" style="color:#fff" class="btn btn-primary btn-lg">search</button>
    </form>

    </th>
</tr>    

    <?php if (isset($this->template)) {
        $count = 0 ?>
        <tr>
         <th>STT</th>
         <th>Name</th>
         <th>Controller</th>
         <th>Action</th>
         <th>Note</th>
         <th>File</th>
         <th style="text-align: center">Action</th>
     </tr>
        <?php foreach ($this->template as $row) {?>
            <?php $file  = '../files/'.$row["file"]; 
            $count=$count+1;?>
            <tr>
            <td><?php echo $count?></td>
            <td><?php echo $row['name']?></td>
            <td><?php echo $row['controller']?></td>
            <td><?php echo $row['action']?></td>
            <td><?php echo $row['note']?></td>
            <td><a target="_bland" href="<?php echo $file?>"><?php echo $row['file'] ?> 
  <i class="fas fa-file"></i></a></td>
            <td style="text-align: center">
                <a href="/index/edit?id=<?php echo $row['id']?>" class="btn btn-warning">Edit</a>

            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
        Delete
      </button>

    
      <div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" >
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Modal Heading</h4>
              <button type="button" class="close"  onClick="window.location.reload()" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <h5>Do you want to delete</h5>
                <iframe name="my_iframe" src="" style="border:none;height:10vh;"></iframe>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary"  onClick="window.location.reload()" data-dismiss="modal">Close</button>
                <form action="/index/delele" method="post" target="my_iframe" enctype="multipart/form-data">
                    <input type='hidden' name='id' value="<?php echo $row['id']; ?>">
                    <button type="submit" class="btn btn-danger">Delele</button>
                </form>
            </div>
    
          </div>
        </div>
      </div>
    
            </td>
            </tr>
                
    <?php }
    } else { ?> 
        <tr><th>Hiện chưa có dữ liệu</th></tr>
        <?php }?>

    <tr>
        
        <th style="text-align: center, cursor: poiner"><a href="../" >back</a></th>
    </tr>
    </table> 
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    </div>
  </div>
</div>
</body>

</html>