<?php 
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Zend Framework Tutorial');

echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> 
<head>
    <?php echo $this->headMeta(); ?> 
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); ?> 
</head>
  <style>
    .main {
      width: 100%;
      height: 100vh;
    }

    .table_template {
      width: 100%;
      display: flex;
      justify-content: center;
    }

    .table_template .form_add_template {
      border: 1px solid #3042ab;
      border-radius: 5%;
      width: 25%;
      height: 80vh;
      padding: 0 5% 0% 5%;
    }

    .form_add_template input,
    textarea {
      border-radius: 5px;
      border: #409dbf 1px solid;
      box-shadow: #000;
      box-sizing: border-box;
      padding: 4% 5% 4% 7%;
    }

    .form_add_template input:hover {
      border: #1f566b 1px solid;
      color: #103746;
    }

    .form_add_template #submit {
      border: #409dbf 1px solid;
      background-color: blue;
      color: #fff;
      cursor: pointer;
    }

    .form_add_template #note {
      word-wrap: break-word;
      padding: 0;
      padding-left: 2%;
    }

    .form_add_template .note_text {
      margin-bottom: 10%;
    }

    .form_add_template #file {
      border: none;
    }

    .form_add_template #submit:hover {
      background-color: #000;
    }

    .form_add_template .form_text {
        margin: 0 5% 5% 0;
    }

    .form_add_template .header {
      text-align: left;
      font-size: 22px;
      padding: 5%;
    }
  </style>
<body>
<div id="content">
    <h1><?php echo $this->escape($this->title); ?></h1>
    <?php echo $this->layout()->content; ?>
</div>

</body>
</html>